homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

blog_list:
    path:     /bloglist/{subjectId}
    defaults: { _controller: AppBundle:Blog:list }

blog_listbytag:
    path:     /bloglistbytag/
    defaults: { _controller: AppBundle:Blog:listbytag }

blog_show:
    path:     /blogshow/
    defaults: { _controller: AppBundle:Blog:show }

blog_show_compitable:
    path:     /blogshow/{blogId}
    defaults: { _controller: AppBundle:Blog:show }

blog_search:
    path:     /blogsearch
    defaults: { _controller: AppBundle:Blog:search }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

qq_login:
    path: /login/check-qq

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

favorite_home:
    path:     /favorite/
    defaults: { _controller: AppBundle:Favorite:index }

favorite_show:
    path:     /favorite/pageshow
    defaults: { _controller: AppBundle:Favorite:show }

favorite_sourcelist:
    path:     /favorite/sourcelist
    defaults: { _controller: AppBundle:Favorite:sourcelist }

favorite_categorylist:
    path:     /favorite/categorylist
    defaults: { _controller: AppBundle:Favorite:categorylist }


pdf_latest:
    path:     /pdf/{title}_{year}_{month}_{day}.pdf
    requirements:
        "year": "201[6-9]"
        "month": "[01]\d"
        "day": "[0123]\d"
    defaults: { _controller: AppBundle:Pdf:generate }